let html =  "<tr>"
  html+=    "<td>"
  html+=       "<input required='required' class='form-control col-lg-7 col-md-3 col-xs-12' type='text' name='productname[]' placeholder='Enter Product name here...'>"
  html+=     "</td>"
  html+=     "</tr>"
  html+=     "<tr>"
  html+=    "<td>"
  html+=       "<input required='required' class='form-control col-lg-7 col-md-3 col-xs-12' type='text' name='productdes[]' placeholder='Enter product description here...'>"
  html+=     "</td>"
  html+=     "</tr>"
  html+=     "<tr>"
  html+=    "<td>"
  html+=       "<input required='required' class='form-control col-lg-7 col-md-3 col-xs-12' type='number' name='productprice[]' placeholder='Enter product price here...>"
  html+=     "</td>"
  html+=     "</tr>"