<?PHP
$filepath = realpath(dirname(__FILE__));
include_once($filepath.'/../config/sql.config.php');
include_once($filepath.'/../config/sql.analytics.php');
include_once($filepath.'/../config/config.php');
include_once($filepath.'/../classes/Generic.php');
class COMPANY extends Generic{
    protected $classname="COMPANY";
    protected $id="COMPANY_ID";
    protected $var=DB_NAME_3;
    protected $var2=DB_NAME_1;
    protected $var3=DB_NAME_2;
    Protected $var4=DB_NAME_5;
    protected $SIGNUP_SELECT=SIGNUP_SELECT;
    protected $SIGNUP_INSERT=SIGNUP_INSERT;
    protected $EMAIL_VERIFICATION_INSERT = EMAIL_VERIFICATION_INSERT;
    protected $VERIFY_ACCOUNT_SELECT=COMPANY_VERIFY_ACCOUNT_SELECT;
    protected $VERIFY_ACCOUNT_UPDATE=COMPANY_VERIFY_ACCOUNT_UPDATE;
    protected $DEFAULTPROFILE_SELECT=COMPANY_DEFAULTPROFILE_SELECT;
    protected $DEFAULTPROFILE_INSERT=COMPANY_DEFAULTPROFILE_INSERT;
    protected $LOGIN_SELECT=LOGIN_SELECT;
    protected $PIMG_SELECT=COMPANY_PIMG_SELECT;
    protected $ADMIN_SELECT=COMPANY_ADMIN_SELECT;
    protected $ADMIN_INSERT=COMPANY_ADMIN_INSERT;
    protected $TEMP_UPDATE=COMPANY_TEMP_UPDATE;
    protected $PASSWORD_UPDATE=COMPANY_PASSWORD_UPDATE;
    protected $PASSWORD_SELECT = COMPANY_PASSWORD_SELECT;
    protected $REGISTER_SELECT=COMPANY_REGISTER_SELECT;
    PROTECTED $REGISTER_INSERT=COMPANY_REGISTER_INSERT;
    protected $TOVIEW1_SELECT1=SMME_TOVIEW1_SELECT1;
    protected $TOVIEW1_SELECT2=SMME_TOVIEW1_SELECT2;
    protected $TOVIEW1_SELECT3=SMME_TOVIEW1_SELECT3;
    protected $TOVIEW1_SELECT_2_1=NPO_TOVIEW1_SELECT1;
    protected $TOVIEW1_SELECT_2_2=NPO_TOVIEW1_SELECT2;
    protected $TOVIEW1_SELECT_2_3=NPO_TOVIEW1_SELECT3;
    protected $ADDCOMPANYSTATEMENTS_SELECT = COMPANY_ADDCOMPANYSTATEMENTS_SELECT;
    protected $ADDCOMPANYSTATEMENTS_INSERT = COMPANY_ADDCOMPANYSTATEMENTS_INSERT;
    protected $PRODUCTS_INSERT = COMPANY_PRODUCT_INSERT;
    protected $BUSINESS_LINKS_INSERT = COMPANY_BUSINESS_LINKS_INSERT;
    protected $COMPARITIVE_CHART = COMPARITIVE_CHART;
    protected $MORE_INFO = SMME_MOREINFO;
    protected $MORE_INFO_CHART = SMME_MOREINFO_CHART;
    protected $COMPANY_TO_COMPANY_VIEW_MORE = COMPANY_MOREINFO;
    protected $PRODUCTS = SMME_PRODUCT_SELECT;
    protected $VALIDATE_CONNECTION = VALIDATE_CONNECTION_SELECT;
    protected $EXPENSESUMMARY_SELECT=SMME_EXPENSESUMMARY_SELECT;
protected $PRODUCT_UPDATE=COMPANY_PRODUCT_UPDATE;
    protected $KEYWORD_INSERT=COMPANY_KEYWORD_INSERT;

    protected $REVIEW_ADMIN_SELECT=COMPANY_REVIEW_ADMIN_SELECT;
    protected $REVIEW_REGISTER_SELECT=COMPANY_REVIEW_REGISTER_SELECT;
    protected $REVIEW_KEYWORDS_SELECT=COMPANY_REVIEW_KEYWORDS_SELECT;
    protected $REVIEW_LINKS_SELECT=COMPANY_REVIEW_LINKS_SELECT;
    protected $LINK_NAME_SELECT=COMPANY_LINKNAME_SELECT;
    protected $COMPANY_ACTIVE=SMME_COMPANY_ACTIVE;

    protected $COMPANYREG_ACTIVE=COMPANY_REGISTER_ACTIVE;

    protected $STATEMENT_COMPANY=STATEMENT_COMPANY_UPDATE;
    protected $COMPANY_UPDATE=COMPANY_PRODUCT_UPDATE;
    protected $COMPANY_DELETE_PRODUCT=COM_PRODUCT_DELETE;

    protected $ADMIN_UPDATE=COMPANY_ADMIN_UPDATE;
    protected $REGISTER_UPDATE=COMPANY_REGISTER_UPDATE;
    protected $KEYWORDS_UPDATE=COMPANY_KEYWORDS_UPDATE;
    protected $LINKS_UPDATE=COMPANY_LINKS_UPDATE;
protected $NOTIFICATION_VIEWED=NOTIFICATION_VIEWED_UPDATE;

    protected $DISPLAY_ADMIN_CHAT_SELECT=DISPLAY_ADMIN_CHAT_SELECT;

    protected $ADMINS_NAVIGATION_SELECT=ADMINS_NAVIGATION_SELECT;
    
   protected $COMPANY_STATE_DELETE=COMPANY_STATE_DELETE;

    protected $ADMIN_DELETE=COMPANY_ADMIN_DELETE;
    protected $REGISTER_DELETE=COMPANY_REGISTER_DELETE;
    protected $LINKS_DELETE=COMPANY_LINKS_DELETE;
    protected $KEYWORDS_DELETE=COMPANY_KEYWORDS_DELETE;
    protected $FETCH_INDUUSTRY_ID=FETCH_INDUUSTRY_ID;
    protected $CONSULTANTS_SELECT=COMPANY_CONSULTANTS_SELECT;
    protected $REVIEW_STATEMENTS_SELECT=COMPANY_REVIEW_STATEMENTS_SELECT;
    protected $REVIEW_PRODUCTS_SELECT=COMPANY_REVIEW_PRODUCTS_SELECT;
    protected $FETCH_LINKS = COMPANY_VIEW_MORE_LINK_SELECT;
    protected $URL_SELECT = COMPANY_URL_SELECT;
    //analytics 
    protected $TOTAL_NUMBER_REQUESTS_SELECT=COMPANY_TOTAL_NUMBER_REQUESTS_SELECT;
    protected $TOTAL_NUMBER_REQUESTS_RECEIVED_SELECT=COMPANY_TOTAL_NUMBER_REQUESTS_RECEIVED_SELECT;
    protected $ENGAGED_ANALYTICS_SELECT=COMPANY_ENGAGED_ANALYTICS_SELECT;
    protected $TOTAL_NUMBER_CONNECTIONS_SELECT=COMPANY_TOTAL_NUMBER_CONNECTIONS_SELECT;
    protected $MORE_INFO_VIEWS_SELECT=COMPANY_MORE_INFO_VIEWS_SELECT;
    protected $WEBSITELINK_VIEWS_SELECT=COMPANY_WEBSITELINK_VIEWS_SELECT;
    protected $VIEWS_INSERT=COMPANY_VIEWS_INSERT;
    protected $KEYWORD_ANALYTICS_SELECT=COMPANY_KEYWORD_ANALYTICS_SELECT;
    protected $KEYWORD_HITS_SELECT=KEYWORD_HITS_SELECT;
    protected $FINALISED_SELECT=COMPANY_FINALISED_SELECT;
    protected $SYSTEM_CONNECTIONS_PER_MONTH_SELECT=SYSTEM_CONNECTIONS_PER_MONTH_SELECT;
    protected $CONNECTIONS_PER_MONTH_SELECT=COMPANY_CONNECTIONS_PER_MONTH_SELECT;
    protected $PROFILE_STATS_SELECT=COMPANY_PROFILE_STATS_SELECT;
    protected $PRODUCT_NAME_SELECT=COMPANY_PRODUCT_NAME_SELECT;
    protected $INDUSTRY_NAME_SELECT=COMPANY_INDUSTRY_NAME_SELECT;
    protected $LEGAL_NAME_SELECT=COMPANY_LEGAL_NAME_SELECT;
}