<?PHP
$filepath = realpath(dirname(__FILE__));
include_once($filepath.'/../config/sql.config.php');
include_once($filepath.'/../classes/Generic.php');
class CONSULTANT extends Generic{
    protected $classname="CONSULTANT";
    protected $id="CONSULTANT_ID";
    protected $var=DB_NAME_4;
    protected $SIGNUP_SELECT=SIGNUP_SELECT;
    protected $SIGNUP_INSERT=SIGNUP_INSERT;
    protected $EMAIL_VERIFICATION_INSERT = EMAIL_VERIFICATION_INSERT;
    protected $DEFAULTPROFILE_SELECT=CONSULTANT_DEFAULTPROFILE_SELECT;
    protected $DEFAULTPROFILE_INSERT=CONSULTANT_DEFAULTPROFILE_INSERT;
    protected $LOGIN_SELECT=LOGIN_SELECT;
    protected $PIMG_SELECT=CONSULTANT_PIMG_SELECT;
    protected $TEMP_UPDATE=CONSULTANT_TEMP_UPDATE;
    protected $ADMIN_SELECT=CONSULTANT_ADMIN_SELECT;
    protected $PASSWORD_UPDATE=CONSULTANT_PASSWORD_UPDATE;
    protected $PASSWORD_SELECT = CONSULTANT_PASSWORD_SELECT;
    protected $ADMIN_INSERT=CONSULTANT_ADMIN_INSERT;
    protected $REGISTER_SELECT=CONSULTANT_REGISTER_SELECT;
    protected $REGISTER_INSERT=CONSULTANT_REGISTER_INSERT;
    protected $REVIEW_ADMIN_SELECT=CONSULTANT_REVIEW_SELECT;
    protected $VERIFY_ACCOUNT_SELECT=CONSULTANT_VERIFY_ACCOUNT_SELECT;
    protected $VERIFY_ACCOUNT_UPDATE=CONSULTANT_VERIFY_ACCOUNT_UPDATE;
    protected $ADMIN_UPDATE=CONSULTANT_ADMIN_UPDATE;
    protected $ADMIN_DELETE = CONSULTANT_ADMIN_DELETE;
    protected $SIGNUP_ADMIN_UPDATE=CONSULTANT_SIGNUP_UPDATE;
}