<?PHP
$filepath = realpath(dirname(__FILE__));//might be a potential error or smart f
include_once($filepath.'/../config/sql.config.php');
include_once($filepath.'/../config/config.php');
include_once($filepath.'/../classes/Generic.php');
include_once($filepath.'/../config/sql.analytics.php');
abstract class MOTHER extends Generic{
    public $id="SMME_ID";
    protected $var=DB_NAME_1;
    protected $var2=DB_NAME_3;
    Protected $var4=DB_NAME_5;
    protected $SIGNUP_SELECT=SIGNUP_SELECT;
    protected $VERIFY_ACCOUNT_SELECT=SMME_VERIFY_ACCOUNT_SELECT;
    protected $VERIFY_ACCOUNT_UPDATE=SMME_VERIFY_ACCOUNT_UPDATE;
    protected $DEFAULTPROFILE_SELECT=SMME_DEFAULTPROFILE_SELECT;
    protected $DEFAULTPROFILE_INSERT=SMME_DEFAULTPROFILE_INSERT;
    protected $LOGIN_SELECT=LOGIN_SELECT;
    protected $PIMG_SELECT=SMME_PIMG_SELECT;
    protected $ADMIN_SELECT=SMME_ADMIN_SELECT;
    protected $ADMIN_SELECT_ACTIVE=SMME_ADMIN_ACTIVE;
    protected $ADMIN_INSERT=SMME_ADMIN_INSERT;
    protected $ADDCOMPANYSTATEMENTS_INSERT=SMME_ADDCOMPANYSTATEMENTS_INSERT;
    protected $ADDCOMPANYSTATEMENTS_SELECT=SMME_ADDCOMPANYSTATEMENTS_SELECT;
    protected $DIRECTORS_SELECT=SMME_DIRECTORS_SELECT;
    protected $DIRECTORS_INSERT=SMME_DIRECTORS_INSERT;
    protected $ADDCOMPANYDOCUMENTS_INSERT=SMME_ADDCOMPANYDOCUMENTS_INSERT;
    protected $EXPENSESUMMARY_INSERT=SMME_EXPENSESUMMARY_INSERT;
    protected $EXPENSESUMMARY_SELECT=SMME_EXPENSESUMMARY_SELECT;
    protected $TEMP_UPDATE=SMME_TEMP_UPDATE;
    protected $REGISTER_SELECT=SMME_REGISTER_SELECT;
    PROTECTED $REGISTER_INSERT=SMME_REGISTER_INSERT;
    protected $REGISTERCOMPANYDATA_SELECT=SMME_REGISTERCOMPANYDATA_SELECT;
    protected $REGISTERCOMPANYDATA_INSERT=SMME_REGISTERCOMPANYDATA_INSERT;
    PROTECTED $STEP_SELECT=SMME_STEP_SELECT;
    // protected $PRODUCTS = COMPANY_PRODUCT_SELECT;
    protected $TOVIEW1_SELECT1=COMPANY_TOVIEW1_SELECT1;
    protected $TOVIEW1_SELECT2=COMPANY_TOVIEW1_SELECT2;
    protected $TOVIEW1_SELECT3=COMPANY_TOVIEW1_SELECT3;
    protected $COMPARITIVE_CHART = COMPARITIVE_CHART;
    protected $MORE_INFO = COMPANY_MOREINFO;
    protected $SMME_tO_SMME_MORE_INFO = SMME_MOREINFO;
    protected $BUSINESS_LINKS_INSERT = SMME_BUSINESS_LINKS_INSERT;
    protected $PRODUCTS = SMME_PRODUCT_SELECT;
    protected $COMPANY_PRODUCTS = COMPANY_PRODUCT_SELECT;
    protected $PRODUCTS_INSERT = SMME_PRODUCT_INSERT;
    protected $EMAIL_VERIFICATION_INSERT = EMAIL_VERIFICATION_INSERT;
    protected $KEYWORD_INSERT=SMME_KEYWORD_INSERT;
    protected $UPLOADFILE_INSERT=SMME_FILEUPLOAD_INSERT;
    protected $REVIEW_SELECT=SMME_REVIEW_SELECT;
    protected $LINK_SMME_NAME_SELECT=SMME_LINKNAME_SELECT;
    protected $SMME_LINK_SELECT=SMME_LINKS_SELECT;
    protected $STATEMENT_SMME_UPDATE=STATEMENT_SMME_UPDATE;
    protected $DOCUMENT_SMME_UPDATE=SMME_UPDATE_DOCUMENTATION;
    protected $ADMIN_SMME_UPDATE=SMME_ADMIN_UPDATE;
    protected $REGISTER_SMME_UPDATE=REGSITER_SMME_UPDATE;
    protected $DIRECTOR_SMME_UPDATE=DIRECTOR_SMME_UPDATE;
    protected $KEYWORDS_UPDATE=COMPANY_ADMIN_UPDATE;
    protected $LINKS_UPDATE=COMPANY_ADMIN_UPDATE;
    protected $PRODUCT_UPDATE=SMME_PRODUCT_UPDATE;
    protected $KEYWORD__SMME_UPDATE=SMME_KEYWORDS_UPDATE;
    protected $FETCH_LINKS = SMME_VIEW_MORE_LINK_SELECT;
    protected $URL_SELECT = SMME_URL_SELECT;
    protected $SMME_ACTIVE_UPDATE=SMME_REGISTER_ACTIVE;
    protected $DOCUMENT_SELECT=SMME_SELECT_ACTIVE;
    protected $PASSWORD_SELECT = SMME_PASSWORD_SELECT;
    //DELETE
    protected $SMME_ADMIN_DELETE=SMME_ADMIN_DELETE;
    protected $SMME_REGISTER_DELETE=SMME_REGISTER_DELETE;
    protected $SMME_DIR_DELETE=SMME_DIR_DELETE;
    protected $SMME_STATE_DELETE=SMME_STATE_DELETE;
    protected $SMME_DOC_DELETE=SMME_DOC_DELETE;
    protected $PASSWORD_UPDATE=SMME_PASSWORD_UPDATE;

    protected $SMME_LINK=SMME_LINK_SELECT;
    protected $PRODUCT_DELETE=PRODUCT_DELETE;

    protected $TOTAL_NUMBER_REQUESTS_RECEIVED_SELECT=SMME_TOTAL_NUMBER_REQUESTS_RECEIVED_SELECT;
    
    protected $TOTAL_NUMBER_CONNECTIONS_SELECT=SMME_TOTAL_NUMBER_CONNECTIONS_SELECT;
    protected $MORE_INFO_VIEWS_SELECT=SMME_MORE_INFO_VIEWS_SELECT;
    protected $WEBSITELINK_VIEWS_SELECT=SMME_WEBSITELINK_VIEWS_SELECT;
    protected $VIEWS_INSERT=SMME_VIEWS_INSERT;
    protected $ENGAGED_ANALYTICS_SELECT=SMME_ENGAGED_ANALYTICS_SELECT;
    protected $KEYWORD_ANALYTICS_SELECT=SMME_KEYWORD_ANALYTICS_SELECT;
    protected $KEYWORD_HITS_SELECT=KEYWORD_HITS_SELECT;
    protected $FINALISED_SELECT=SMME_FINALISED_SELECT;
    protected $SYSTEM_CONNECTIONS_PER_MONTH_SELECT=SYSTEM_CONNECTIONS_PER_MONTH_SELECT;
    protected $CONNECTIONS_PER_MONTH_SELECT=SMME_CONNECTIONS_PER_MONTH_SELECT;
    protected $PROFILE_STATS_SELECT=SMME_PROFILE_STATS_SELECT;

    protected $PRODUCT_NAME_SELECT=SMME_PRODUCT_NAME_SELECT;
    protected $INDUSTRY_NAME_SELECT=SMME_INDUSTRY_NAME_SELECT;
    protected $LEGAL_NAME_SELECT=SMME_LEGAL_NAME_SELECT;
    
}